# golangci-lint configuration
version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    # Default linters (always enabled)
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    
    # Additional useful linters
    - bodyclose
    - dupl
    - goconst
    - gocritic
    - gocyclo
    - revive
    - mnd
    - gosec
    - misspell
    - unconvert
    - unparam
    - whitespace
    - rowserrcheck
    - noctx

linters-settings:
  govet:
    shadow: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - dupl
        - goconst
    - text: "mnd: Magic number"
      linters:
        - mnd